# 文件路径: .github/workflows/docker-ghcr.yml
name: Build and Push to GHCR

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]  # 可选：标签触发（例如 v1.0.0）

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # 必须授权以推送镜像到 GHCR

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}  # 自动使用当前 GitHub 用户
          password: ${{ secrets.GITHUB_TOKEN }}  # GitHub 自动生成的 Token

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .  # Dockerfile 所在目录
          push: true  # 只有 push 时才上传镜像
          tags: |
            ghcr.io/${{ github.repository_owner }}/iscsi-manager:latest
            ghcr.io/${{ github.repository_owner }}/iscsi-manager:${{ github.sha }}
          labels: |
            maintainer="可爱的小cherry"
            org.opencontainers.image.source=${{ github.repositoryUrl }}
